### ISSUE TITLE
how to obtain gunpowder and neurolight.gunpowder?

### ISSUE THREAD

**Issue by zhangyuxuann** [Kainmueller-Lab/PatchPerPix_experiments#1]
1. Program stuck on this line，which i think is related to gunpowder
![image](https://user-images.githubusercontent.com/32118018/93358975-af599580-f874-11ea-830e-60af32fb7cf8.png)

2. GPU utilization is very strange for any different batchsize? No matter how much I set it to, it will fill up the memory. For example, I set batchsize=1 and num_gpu=1, it display as follows.
![image](https://user-images.githubusercontent.com/32118018/93359807-99000980-f875-11ea-9160-dc41452b9b92.png)

3. By the way, can you share the specific environment, which would really help to reproduce this great work?

**Comment by abred** [comment]
thanks for the note!
neurolight: https://github.com/maisli/neurolight
gunpowder: https://github.com/Kainmueller-Lab/gunpowder/tree/v1.0-dev_peter

**Comment by abred** [comment]
2. That is typical Tensorflow behaviour, it just allocates the whole GPU in the beginning and then uses some internal allocator to optimize the placement.

**Comment by abred** [comment]
1. Could you please try the gunpowder linked above and let me know if it is still stuck?

**Comment by abred** [comment]
3. 
```
absl-py @ file:///home/conda/feedstock_root/build_artifacts/absl-py_1598382273190/work
appdirs==1.4.4
asciitree==0.3.3
astor @ file:///home/conda/feedstock_root/build_artifacts/astor_1593610464257/work
augment-nd==0.1.1
brotlipy==0.7.0
certifi==2020.6.20
cffi @ file:///tmp/build/80754af9/cffi_1598370813909/work
chardet==3.0.4
cliez==2.1.1
colorcet==2.0.2
cryptography @ file:///tmp/build/80754af9/cryptography_1598892037289/work
cycler==0.10.0
Cython @ file:///tmp/build/80754af9/cython_1594831564311/work
dask==2.25.0
decorator==4.4.2
-e git+git@github.com:Kainmueller-Lab/evaluate-instance-detection.git@72c394a5c44ce3a6bb5436571231bc72c1bb7bd4#egg=evaluate_instance_detection
-e git+git@github.com:Kainmueller-Lab/evaluate-instance-segmentation.git@7c27b625ec95a34484e491ced762c84b437eb718#egg=evaluate_instance_segmentation
fasteners==0.15
-e git+git@github.com:Kainmueller-Lab/funlib.learn.tensorflow.git@a521614484423e3118ce024758d350b17f81b84d#egg=funlib.learn.tensorflow
future==0.18.2
gast==0.2.2
google-pasta==0.2.0
grpcio @ file:///home/conda/feedstock_root/build_artifacts/grpcio_1596715635580/work
-e git+git@github.com:Kainmueller-Lab/gunpowder.git@82aacc62b5804747315f914e9f185b1923e2514e#egg=gunpowder
h5py @ file:///home/conda/feedstock_root/build_artifacts/h5py_1595110162077/work
idna @ file:///tmp/build/80754af9/idna_1593446292537/work
imageio==2.9.0
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1593211369179/work
joblib @ file:///tmp/build/80754af9/joblib_1594236160679/work
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.2.0
Mako==1.1.3
-e git+https://github.com/TuragaLab/malis.git@2206fe01bd2d10c3bc6a861897820731d1ae131b#egg=malis
Markdown @ file:///home/conda/feedstock_root/build_artifacts/markdown_1589366472132/work
MarkupSafe==1.1.1
matplotlib==3.3.1
monotonic==1.5
natsort==7.0.1
networkx==2.5
-e git+https://github.com/maisli/neurolight.git@4a4a297dfdb6dbf064cd267c740331dec20f4b13#egg=neurolight
numcodecs==0.6.4
numpy @ file:///home/conda/feedstock_root/build_artifacts/numpy_1597938346492/work
opt-einsum==0+untagged.61.gd905544.dirty
param==1.9.3
-e git+git@github.com:Kainmueller-Lab/PatchPerPix_private.git@393f257e628efeb5a2a93a53efb90345b7ec93ed#egg=PatchPerPix
Pillow==7.2.0
protobuf==3.13.0
psutil==5.7.2
pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
pyct==0.4.6
pycuda==2019.1.2
pynrrd==0.4.2
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1594392929924/work
pyparsing==2.4.7
PySocks @ file:///tmp/build/80754af9/pysocks_1594394576006/work
python-dateutil==2.8.1
python-louvain==0.14
pytools==2020.4
PyWavelets==1.1.1
PyYAML==5.3.1
requests @ file:///tmp/build/80754af9/requests_1592841827918/work
scikit-image==0.17.2
scipy @ file:///home/conda/feedstock_root/build_artifacts/scipy_1595583586868/work
six @ file:///home/conda/feedstock_root/build_artifacts/six_1590081179328/work
tensorboard==1.15.0
tensorflow==1.15.0
tensorflow-estimator==1.15.1
termcolor==1.1.0
tifffile==2020.8.25
toml==0.10.1
toolz==0.10.0
urllib3 @ file:///tmp/build/80754af9/urllib3_1597086586889/work
Werkzeug==0.16.1
wrapt==1.12.1
zarr==2.4.0
zipp==3.1.0
```

**Comment by zhangyuxuann** [comment]
> ```
> absl-py @ file:///home/conda/feedstock_root/build_artifacts/absl-py_1598382273190/work
> appdirs==1.4.4
> asciitree==0.3.3
> astor @ file:///home/conda/feedstock_root/build_artifacts/astor_1593610464257/work
> augment-nd==0.1.1
> brotlipy==0.7.0
> certifi==2020.6.20
> cffi @ file:///tmp/build/80754af9/cffi_1598370813909/work
> chardet==3.0.4
> cliez==2.1.1
> colorcet==2.0.2
> cryptography @ file:///tmp/build/80754af9/cryptography_1598892037289/work
> cycler==0.10.0
> Cython @ file:///tmp/build/80754af9/cython_1594831564311/work
> dask==2.25.0
> decorator==4.4.2
> -e git+git@github.com:Kainmueller-Lab/evaluate-instance-detection.git@72c394a5c44ce3a6bb5436571231bc72c1bb7bd4#egg=evaluate_instance_detection
> -e git+git@github.com:Kainmueller-Lab/evaluate-instance-segmentation.git@7c27b625ec95a34484e491ced762c84b437eb718#egg=evaluate_instance_segmentation
> fasteners==0.15
> -e git+git@github.com:Kainmueller-Lab/funlib.learn.tensorflow.git@a521614484423e3118ce024758d350b17f81b84d#egg=funlib.learn.tensorflow
> future==0.18.2
> gast==0.2.2
> google-pasta==0.2.0
> grpcio @ file:///home/conda/feedstock_root/build_artifacts/grpcio_1596715635580/work
> -e git+git@github.com:Kainmueller-Lab/gunpowder.git@82aacc62b5804747315f914e9f185b1923e2514e#egg=gunpowder
> h5py @ file:///home/conda/feedstock_root/build_artifacts/h5py_1595110162077/work
> idna @ file:///tmp/build/80754af9/idna_1593446292537/work
> imageio==2.9.0
> importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1593211369179/work
> joblib @ file:///tmp/build/80754af9/joblib_1594236160679/work
> Keras-Applications==1.0.8
> Keras-Preprocessing==1.1.0
> kiwisolver==1.2.0
> Mako==1.1.3
> -e git+https://github.com/TuragaLab/malis.git@2206fe01bd2d10c3bc6a861897820731d1ae131b#egg=malis
> Markdown @ file:///home/conda/feedstock_root/build_artifacts/markdown_1589366472132/work
> MarkupSafe==1.1.1
> matplotlib==3.3.1
> monotonic==1.5
> natsort==7.0.1
> networkx==2.5
> -e git+https://github.com/maisli/neurolight.git@4a4a297dfdb6dbf064cd267c740331dec20f4b13#egg=neurolight
> numcodecs==0.6.4
> numpy @ file:///home/conda/feedstock_root/build_artifacts/numpy_1597938346492/work
> opt-einsum==0+untagged.61.gd905544.dirty
> param==1.9.3
> -e git+git@github.com:Kainmueller-Lab/PatchPerPix_private.git@393f257e628efeb5a2a93a53efb90345b7ec93ed#egg=PatchPerPix
> Pillow==7.2.0
> protobuf==3.13.0
> psutil==5.7.2
> pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
> pyct==0.4.6
> pycuda==2019.1.2
> pynrrd==0.4.2
> pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1594392929924/work
> pyparsing==2.4.7
> PySocks @ file:///tmp/build/80754af9/pysocks_1594394576006/work
> python-dateutil==2.8.1
> python-louvain==0.14
> pytools==2020.4
> PyWavelets==1.1.1
> PyYAML==5.3.1
> requests @ file:///tmp/build/80754af9/requests_1592841827918/work
> scikit-image==0.17.2
> scipy @ file:///home/conda/feedstock_root/build_artifacts/scipy_1595583586868/work
> six @ file:///home/conda/feedstock_root/build_artifacts/six_1590081179328/work
> tensorboard==1.15.0
> tensorflow==1.15.0
> tensorflow-estimator==1.15.1
> termcolor==1.1.0
> tifffile==2020.8.25
> toml==0.10.1
> toolz==0.10.0
> urllib3 @ file:///tmp/build/80754af9/urllib3_1597086586889/work
> Werkzeug==0.16.1
> wrapt==1.12.1
> zarr==2.4.0
> zipp==3.1.0
> ```

thank you very much!

**Comment by zhangyuxuann** [comment]
> 1. Could you please try the gunpowder linked above and let me know if it is still stuck?

Yes, I find gunpowder in  https://github.com/Kainmueller-Lab/gunpowder/tree/v1.0-dev_peter. It works fine.

**Comment by GalSang17** [comment]
> 1. Program stuck on this line，which i think is related to gunpowder
>    ![image](https://user-images.githubusercontent.com/32118018/93358975-af599580-f874-11ea-830e-60af32fb7cf8.png)
> 2. GPU utilization is very strange for any different batchsize? No matter how much I set it to, it will fill up the memory. For example, I set batchsize=1 and num_gpu=1, it display as follows.
>    ![image](https://user-images.githubusercontent.com/32118018/93359807-99000980-f875-11ea-9160-dc41452b9b92.png)
> 3. By the way, can you share the specific environment, which would really help to reproduce this great work?

嗨，张宇轩你好，我想请教你一些使用PatchPerPix的问题，我的邮箱是galsang117@gmail.com，希望得到你的回复，谢谢
