### ISSUE TITLE
NameError: name 'Point' is not defined

### ISSUE THREAD

**Issue by ShirleySyh** [Kainmueller-Lab/PatchPerPix_experiments#11]
Hi, I met a problem when running run_ppp.py. Here below the error:
![Point](https://user-images.githubusercontent.com/52872919/202657885-49e8c47f-e171-422a-8736-dfca6d1f73f0.png)
Can someone help to see this problem please?
Thanks!

**Comment by abred** [comment]
Hi,

`Point` used to be a class in `gunpowder`, it got removed in newer versions. However we never updated `PatchPerPix` to be compatible with newer versions. If `python` cannot find it it might mean that somehow you got the wrong version of gunpowder.
Did you follow the installation instructions or did you install `gunpowder` separately? Could you please tell me which version/git commit of gunpowder you have installed and if there is a file `gunpowder/points.py`?

**Comment by ShirleySyh** [comment]
> Hi,
> 
> `Point` used to be a class in `gunpowder`, it got removed in newer versions. However we never updated `PatchPerPix` to be compatible with newer versions. If `python` cannot find it it might mean that somehow you got the wrong version of gunpowder. Did you follow the installation instructions or did you install `gunpowder` separately? Could you please tell me which version/git commit of gunpowder you have installed and if there is a file `gunpowder/points.py`?

Hi, 

First of all, thank you very much for your reply. I installed `gunpower ` separately. Its version is 1.2.2 and it seems there isn't a file `gunpower/points.py`.

**Comment by abred** [comment]
Yes, that is too new. In general it would be good if you could use the installation guidelines as outlined in the Readme. Especially for `gunpowder`; please make sure that you are at commit `a53bb55edc2d28a1acb310971571984cf0771cab`
```
git+https://github.com/Kainmueller-Lab/gunpowder.git@a53bb55edc2d28a1acb310971571984cf0771cab#egg=gunpowder
```
