### ISSUE TITLE
Hello, I have some problems that are bothering me so far, I hope to get your help ^_^

### ISSUE THREAD

**Issue by GalSang17** [Kainmueller-Lab/PatchPerPix_experiments#3]
![image](https://user-images.githubusercontent.com/49866330/100073640-bacecb80-2e78-11eb-8a05-5fa465d33344.png)

When I use the following command to predict, an error will be reported in the decode stage. Another problem is that when predicting, only the first file in the test folder will be predicted, and when the second file is reached It's stuck, and there will be no prompt output
![image](https://user-images.githubusercontent.com/49866330/100073481-8824d300-2e78-11eb-8368-67306d31a5c4.png)

**Comment by abred** [comment]
Hi, this might be related to your commend in #2 regarding the fork decorator. Tensorflow seems to sometimes have a problem with reinitialization or something like that, we are not sure, but that's one reason why we use fork sometimes, in a slightly hacky way. But otherwise it gets stuck after the first file.
I am not sure about the lock error, haven't seen it, does it still happen when you uncomment the fork decorator?

**Comment by GalSang17** [comment]
> Hi, this might be related to your commend in #2 regarding the fork decorator. Tensorflow seems to sometimes have a problem with reinitialization or something like that, we are not sure, but that's one reason why we use fork sometimes, in a slightly hacky way. But otherwise it gets stuck after the first file.
> I am not sure about the lock error, haven't seen it, does it still happen when you uncomment the fork decorator?

![image](https://user-images.githubusercontent.com/49866330/100183081-09cc3d80-2f19-11eb-95ca-02b52fcc009d.png)
I tried to uncomment the fork decorator, but it was still stuck in the second file when predicting. There was a strange phenomenon. The instanced folder generated after running the predict.py file was empty, and then I When I use evaluate to do experiments, the error shown in the figure above will occur. I don't quite understand what files should be generated in the processed, instanced, and evaluated folders. And what effect will predict and evaluate and visualize show? How do I get a segmentation effect picture like the one shown in your paper after my training, like the following
![image](https://user-images.githubusercontent.com/49866330/100183302-85c68580-2f19-11eb-816b-8cf4746652cd.png)

**Comment by GalSang17** [comment]
If you can provide a readme file from training to prediction, evaluation, and visualization, I would be very grateful. I think it will also help solve many of the troubles of many people who want to use this project. I look forward to your reply.^_^

**Comment by abred** [comment]
I am sorry for your troubles and thank you for your patience!

(The error you get above just happens if one of the steps before evaluation fails, but I should probably catch it and provide a more meaningful error message)

Did you fork the code/do you have your current state accessible somewhere? 

I just updated the requirements.txt file to fix the gunpowder version to a specific commit. Could you please (after pulling) execute `pip install -r requirements.txt --upgrade` to make sure that you are using the correct gunpowder version (I recently pushed some new code that does not yet seem to be compatible to PatchPerPix, sorry for that)

I also just ran it from scratch, there were some minor problems that I pushed fixes for, but besides that, it works for me.

The image you posted is a visualization of the generated label image, stored under `instanced`. One way to view it is using `Fiji`, alternatively you can load it in python with `h5py` and e.g. convert it with `skimage` or plot it.

**Comment by GalSang17** [comment]
> Did you fork the code/do you have your current state accessible somewhere?

Sorry, I am a bit busy these days, so I reply to your message. I didn't use fork in the code, it will report an error. In addition, I can use pdb to track my variables. Now I have not found any problems during training, but execute the following command (CUDA_VISIBLE_DEVICES=1 python run_ppp.py --setup setup08 --config experiments/wormbodies_setup08_201126_074703/config.toml --do validate predict decode label evaluate visualize --app wormbodies -id experiments/wormbodies_setup08_201126_074703
) Is the same effect as the screenshot I gave last time. It will return a nan, but a .hdf file will appear in the instanced folder. When I use h5py to view its value, all the values are 0, and when I save the read array in png or jpg format, an error will be reported. Save it as bmp, but it can’t be opened. All operations are like the picture below. I look forward to your reply ^_^.
![image](https://user-images.githubusercontent.com/49866330/100721802-c5e6a600-33fa-11eb-9e68-8c94b9905178.png)

**Comment by abred** [comment]
I'm sorry, I did not mean if you used fork in the code, I meant if you forked/copied the repository somewhere, do you have your modified code on github? So that I can see what changes you made. It is hard to debug it otherwise.

I don't think predicting multiple images will work without fork, what is the error you get?
The errors in your screenshot above are natural as long as something fails in an earlier stage of the pipeline. Could you please try and delete all instances/processed/evaluated folders in your experiment folder (under val/ and test/) and run your command again

**Comment by GalSang17** [comment]
> I'm sorry, I did not mean if you used fork in the code, I meant if you forked/copied the repository somewhere, do you have your modified code on github? So that I can see what changes you made. It is hard to debug it otherwise.
> 
> I don't think predicting multiple images will work without fork, what is the error you get?
> The errors in your screenshot above are natural as long as something fails in an earlier stage of the pipeline. Could you please try and delete all instances/processed/evaluated folders in your experiment folder (under val/ and test/) and run your command again

Sorry, I misunderstood, I did not fork the code on your github, the code is kept as originally submitted by you. But the effect of commenting out the fork decorator is the same as that of not commenting. The predictions of multiple images are still stuck in the second image as before, so my test folder is currently artificially placed by myself. I entered a test file. The last suggestion you mentioned later, I re-run my command, but the problem of multiprocessing process pool always appears, which I mentioned before, like the following
![image](https://user-images.githubusercontent.com/49866330/100732414-a73adc00-3407-11eb-9620-d7c636234200.png)

**Comment by GalSang17** [comment]
> > I'm sorry, I did not mean if you used fork in the code, I meant if you forked/copied the repository somewhere, do you have your modified code on github? So that I can see what changes you made. It is hard to debug it otherwise.
> > I don't think predicting multiple images will work without fork, what is the error you get?
> > The errors in your screenshot above are natural as long as something fails in an earlier stage of the pipeline. Could you please try and delete all instances/processed/evaluated folders in your experiment folder (under val/ and test/) and run your command again
> 
> Sorry, I misunderstood, I did not fork the code on your github, the code is kept as originally submitted by you. But the effect of commenting out the fork decorator is the same as that of not commenting. The predictions of multiple images are still stuck in the second image as before, so my test folder is currently artificially placed by myself. I entered a test file. The last suggestion you mentioned later, I re-run my command, but the problem of multiprocessing process pool always appears, which I mentioned before, like the following
> ![image](https://user-images.githubusercontent.com/49866330/100732414-a73adc00-3407-11eb-9620-d7c636234200.png)

Even if I change the number of all num_workers processes in the configuration file to 1, this error will continue.

**Comment by abred** [comment]
Did you pull my changes from a few days ago? And if you do a `git diff` there are no changes? hmm I don't really get it, the error you posted happens before forks or locks are even used.

**Comment by GalSang17** [comment]
> Did you pull my changes from a few days ago? And if you do a `git diff` there are no changes? hmm I don't really get it, the error you posted happens before forks or locks are even used.

I used the newly submitted code a few days ago and re-pulled a copy to my project, but did not do git diff, because the re-pulled project itself is exactly what you submitted. Regarding the lock issue, I We are actively looking for a solution. Some people in stackoverflow mentioned that from queue import Queue was changed to from multiprocessing import Queue, but I noticed that you did this. Another solution is to change the start() method of the process to I also tried the run() method, but it didn’t work. I’m very confused now^@^

**Comment by abred** [comment]
The thing is, there should not be a lock object in the config at this point. Could you please add a `print(config)` statement before the `val_config = deepcopy(config)` line causing the exception above and post the output here?

**Comment by GalSang17** [comment]
> The thing is, there should not be a lock object in the config at this point. Could you please add a `print(config)` statement before the `val_config = deepcopy(config)` line causing the exception above and post the output here?

I added a statement to print config here like you said
![image](https://user-images.githubusercontent.com/49866330/100737093-aeb1b380-340e-11eb-9052-415ed31644c8.png)
The result it produces is like this
![image](https://user-images.githubusercontent.com/49866330/100737362-0a7c3c80-340f-11eb-961c-3df8ac627bbc.png)

**Comment by abred** [comment]
can you post it as text please :)

**Comment by abred** [comment]
hm and in this case there as no exception afterwards? Can you please post the output of this print statement just before the exception

**Comment by GalSang17** [comment]
> hm and in this case there as no exception afterwards? Can you please post the output of this print statement just before the exception

----------------> {'base': 'experiments/wormbodies_setup08_201126_074703', 'general': {'logging': 20, 'debug': False, 'overwrite': False}, 'data': {'train_data': '/home/zhao412/jiang451/PatchPerPix/PatchPerPix_e
xperiments/wormbodies/01_data/imgs/datasets/train', 'val_data': '/home/zhao412/jiang451/PatchPerPix/PatchPerPix_experiments/wormbodies/01_data/imgs/datasets/test', 'test_data': '/home/zhao412/jiang451/PatchPerPi
x/PatchPerPix_experiments/wormbodies/01_data/imgs/datasets/test', 'voxel_size': [1, 1], 'input_format': 'zarr', 'raw_key': 'volumes/raw_bf', 'gt_key': 'volumes/gt_instances', 'one_instance_per_channel_gt': 'volu
mes/gt_labels', 'num_channels': 1, 'validate_on_train': False}, 'model': {'train_net_name': 'train_net', 'test_net_name': 'test_net', 'train_input_shape': [256, 256], 'test_input_shape': [512, 512], 'patchshape'
: [1, 41, 41], 'patchstride': [1, 1, 1], 'num_fmaps': 40, 'max_num_inst': 2, 'fmap_inc_factors': [2, 2, 2, 2], 'fmap_dec_factors': [1, 1, 1, 1], 'downsample_factors': [[2, 2], [2, 2], [2, 2], [2, 2]], 'activatio
n': 'relu', 'padding': 'valid', 'kernel_size': 3, 'num_repetitions': 2, 'upsampling': 'resize_conv', 'overlapping_inst': True, 'code_units': 252, 'autoencoder_chkpt': 'this'}, 'optimizer': {'optimizer': 'Adam', 
'lr': 0.0001}, 'preprocessing': {'clipmax': 1500}, 'training': {'batch_size': 1, 'num_gpus': 5, 'num_workers': 6, 'cache_size': 40, 'max_iterations': 40000, 'checkpoints': 2000, 'snapshots': 200, 'profiling': 50
0, 'train_code': True, 'sampling': {'min_masked': 0.001, 'min_masked_overlap': 0.0001, 'overlap_min_dist': 0, 'overlap_max_dist': 15, 'probability_overlap': 0.5, 'probability_fg': 0.5}, 'augmentation': {'elastic
': {'control_point_spacing': [10, 10], 'jitter_sigma': [1, 1], 'rotation_min': -45, 'rotation_max': 45}, 'intensity': {'scale': [0.9, 1.1], 'shift': [-0.1, 0.1]}, 'simple': {}}}, 'prediction': {'output_format': 
'zarr', 'aff_key': 'volumes/pred_affs', 'code_key': 'volumes/pred_code', 'fg_key': 'volumes/pred_numinst', 'fg_thresh': 0.5, 'decode_batch_size': 1024}, 'validation': {}, 'testing': {'num_workers': 5}, 'vote_ins
tances': {'patch_threshold': 0.9, 'fc_threshold': 0.5, 'cuda': True, 'blockwise': False, 'num_workers': 8, 'chunksize': [92, 92, 92], 'select_patches_for_sparse_data': True, 'save_no_intermediates': True, 'outpu
t_format': 'hdf', 'parallel': False, 'includeSinglePatchCCS': True, 'sample': 1.0, 'removeIntersection': True, 'mws': False, 'isbiHack': False, 'mask_fg_border': False, 'graphToInst': False, 'skipLookup': False,
 'skipConsensus': False, 'skipRanking': False, 'skipThinCover': True, 'affinity_graph_voting': False, 'affinity_graph_voting_selected': False, 'termAfterThinCover': False, 'fg_thresh_vi': 0.1, 'consensus_interle
aved_cnt': False, 'consensus_norm_prob_product': True, 'consensus_prob_product': True, 'consensus_norm_aff': True, 'vi_bg_use_inv_th': False, 'vi_bg_use_half_th': False, 'vi_bg_use_less_than_th': True, 'rank_nor
m_patch_score': True, 'rank_int_counter': False, 'patch_graph_norm_aff': True, 'blockwise_old_stitch_fn': False, 'only_bb': False, 'flip_cons_arr_axes': False, 'return_intermediates': False}, 'evaluation': {'num
_workers': 1, 'res_key': 'vote_instances', 'metric': 'confusion_matrix.th_0_5.AP'}, 'postprocessing': {'remove_small_comps': 600, 'watershed': {'output_format': 'hdf'}}, 'visualize': {'samples_to_visualize': ['A
10', 'C17'], 'show_patches': True}, 'autoencoder': {'train_net_name': 'train_net', 'test_net_name': 'test_net', 'train_input_shape': [1, 41, 41], 'test_input_shape': [1, 41, 41], 'patchshape': [1, 41, 41], 'patc
hstride': [1, 1, 1], 'network_type': 'conv', 'activation': 'relu', 'code_activation': 'sigmoid', 'encoder_units': [500, 1000], 'decoder_units': [1000, 500], 'num_fmaps': [32, 64, 128], 'downsample_factors': [[2,
 2], [2, 2], [2, 2]], 'upsampling': 'resize_conv', 'kernel_size': 3, 'num_repetitions': 2, 'padding': 'same', 'code_method': 'conv1x1', 'code_units': 252, 'regularizer': 'l2', 'regularizer_weight': 0.0001, 'loss
_fn': 'mse', 'overlapping_inst': False, 'only_decode': True, 'dummy_in': <tf.Tensor 'Placeholder:0' shape=(?, 41, 41) dtype=float32>, 'is_training': True, 'input_shape_squeezed': (41, 41)}}                      
Traceback (most recent call last):                                                                                                                                                                                 
  File "run_ppp.py", line 1590, in <module>                                                                                                                                                                        
    main()                                                                                                                                                                                                         
  File "run_ppp.py", line 1470, in main                                                                                                                                                                            
    train_folder, test_folder, output_folder)

**Comment by abred** [comment]
hmm, can you please post the whole log file?

**Comment by GalSang17** [comment]
> hmm, can you please post the whole log file?

Can I send it to your mailbox?The size is too big!

**Comment by GalSang17** [comment]
> hmm, can you please post the whole log file?

**Comment by abred** [comment]
peter.hirsch@mdc-berlin.de (or maybe upload it to dropbox/google drive etc and link it here)

**Comment by GalSang17** [comment]
> [peter.hirsch@mdc-berlin.de](mailto:peter.hirsch@mdc-berlin.de) (or maybe upload it to dropbox/google drive etc and link it here)

I have sent run.log to your mailbox :)

**Comment by abred** [comment]
I don't understand why it is processing checkpoint 38000 when you trained until 40000.
hmm could you please try to start a new experiment from scratch, you can change max_iterations in the config.toml file to 2000 or something like that, just to test it.

**Comment by GalSang17** [comment]
> I don't understand why it is processing checkpoint 38000 when you trained until 40000.
> hmm could you please try to start a new experiment from scratch, you can change max_iterations in the config.toml file to 2000 or something like that, just to test it.

This is the case, I first train the model iteratively for 40,000 rounds, and then I modified the --checkpoint parameter (38000) in run_ppp.py, as the picture shows, not all checkpoints are verified during training. 
![image](https://user-images.githubusercontent.com/49866330/100827783-840c3d00-3498-11eb-8f5f-25c28cd654a4.png)
So you will see that it only verifies the effect of checkpoint38000. Is there anything wrong with this? In addition, I will conduct a new experiment as soon as possible, just like the Usage mentioned in the README to run the command. I will continue to ask if there are any questions :)

**Comment by GalSang17** [comment]
> I don't understand why it is processing checkpoint 38000 when you trained until 40000.
> hmm could you please try to start a new experiment from scratch, you can change max_iterations in the config.toml file to 2000 or something like that, just to test it.

I completed a new experiment, but the problem is still the same. After the training is over, an error will be reported immediately. The command is as follows:
CUDA_VISIBLE_DEVICES=1,2,3,4 python run_ppp.py --setup setup08 --config wormbodies/02_setups/setup08/config.toml --do mknet train validate_checkpoints predict decode label evaluate visualize --app wormbodies --root experiments

**Comment by abred** [comment]
can you send me that new log as well, please?

**Comment by GalSang17** [comment]
> can you send me that new log as well, please?

Ok, I will send you email

**Comment by Paragjain10** [comment]
Traceback (most recent call last):
File "/home/student2/Desktop/Parag_masterthesis/PatchPerPix/PatchPerPix_experiments/run_ppp.py", line 1588, in
main()
File "/home/student2/Desktop/Parag_masterthesis/PatchPerPix/PatchPerPix_experiments/run_ppp.py", line 1377, in main
quantity=config['training']['num_gpus'])
File "/home/student2/Desktop/Parag_masterthesis/PatchPerPix/PatchPerPix/util/selectGPU.py", line 27, in selectGPU
pid = ln.split()[1]
IndexError: list index out of range

Has anybody faced the same issue?
Can you help me with this?
Thank you!

**Comment by abred** [comment]
@GalSang17 did you get my email two weeks ago?
