### ISSUE TITLE
ModuleNotFoundError: No module named 'PatchPerPix'

### ISSUE THREAD

**Issue by jtyytim** [Kainmueller-Lab/PatchPerPix_experiments#6]
Hello,

I followed your tutorial for all installations, but when I launched the example code for usage. I got this error:
![image](https://user-images.githubusercontent.com/35915517/118476225-880ddd80-b70d-11eb-9378-ebe5df67410d.png)
Can someone help to see this problem please?

Thanks,
Thiem

**Comment by abred** [comment]
Hello Thiem,

did you do the first step in the Readme?
"First install the core code: [PatchPerPix](https://github.com/Kainmueller-Lab/PatchPerPix). Then continue here."

**Comment by jtyytim** [comment]
Yes, I did it last time. And this time I tried to follow it again but I got this problem after here:
![image](https://user-images.githubusercontent.com/35915517/118484864-fe174200-b717-11eb-9e1d-adf24463afe9.png)

![image](https://user-images.githubusercontent.com/35915517/118485067-36b71b80-b718-11eb-8e1e-aca2f391193c.png)

![image](https://user-images.githubusercontent.com/35915517/118484977-2141f180-b718-11eb-8c20-45daf47b1ade.png)

Do you know how I can fix it?
Thanks,

Thiem

**Comment by abred** [comment]
It can't find nvcc (nvidia cuda compiler), so something seems to be wrong with your cuda installation. Do you have cuda installed on this machine?

**Comment by jtyytim** [comment]
From nvidia-smi, I think I got cuda, non?
[image: image.png]

**Comment by abred** [comment]
I cannot see the image, but I think nvidia-smi only tells you about the graphics driver, that is not enough, you need the cuda toolkit (for development)
